using RHP.Entities.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RHP.Entities.Models
{
    public enum UserRole
    {
        Player,
        Admin
    }

    public enum UserStatus
    {
        Online,
        Away,
        Offline
    }
    public class User
    {
        [Key]
        public string Id { get; set; } //User id is the only Id that is not autogenerated by the database
        public required string Email { get; set; }

        public required string Password { get; set; }

        public Player? Player { get; set; }

        public bool active { get; set; } 

        public UserRole Role { get; set; }

        public bool loggedIn { get; set; }

        public required DateTime lastLogin { get; set; }

        public UserStatus Status { get; set; }

        public ICollection<Contact> Contacts { get; set; }

        public override string? ToString() => Email;

        public User() {
            active = true; //TODO: Must be set false once Email autentication is implemented
            Role = UserRole.Player;
            loggedIn = false;
            Status = UserStatus.Online;
        }
    }
}
